---
project: api.data.gov
name: api-data-gov
github:
- 18F/api.data.gov
- NREL/api-umbrella
description: 'A hosted, shared-service that provides an API key, analytics, and proxy
  solution for government web services. We are currently accepting clients for this
  free service: contact us to learn more.'
partners:
- Broadcasting Board of Governors
- BusinessUSA.gov
- Department of Agriculture
- Department of Commerce
- Department of Education
- Federal Election Commission
- Federal Communications Commission
- Food and Drug Administration
- General Services Administration
- National Aeronautics and Space Administration
- National Institutes of Health
- National Renewable Energy Laboratory
- Regulations.gov
stage: beta
impact: 2,800 API users and 66 million API requests served since July 2013
milestones: 
contact:
- api.data.gov@gsa.gov
stack: JavaScript (Node and Ember), Rails, nginx, elasticsearch, Varnish, redis, and
  MongoDB
team: gray
licenses:
  fbopen: Public Domain (CC0)
links:
- https://api.data.gov
- https://api.data.gov/metrics
- https://api.data.gov/about
blog:
- API
status: 
