baseURL: /
languageCode: en-us
title: api.data.gov
params:
  githubRepoUrl: https://github.com/18F/api.data.gov
  apiUmbrellaContactApiKey: DEMO_KEY
  apiUmbrellaSignupApiKey: DEMO_KEY
markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    style: github
menu:
  main:
    - identifier: docs
      name: API Docs
      pageRef: /docs/
    - identifier: signup
      name: API Key Signup
      pageRef: /signup.html
sectionPagesMenu: main
module:
  mounts:
    - source: content
      target: content
    - source: static
      target: static
    - source: layouts
      target: layouts
    - source: data
      target: data
    - source: assets
      target: assets
    - source: i18n
      target: i18n
    - source: archetypes
      target: archetypes
    - source: ./node_modules/@uswds/uswds/dist/fonts/
      target: static/node_modules/@uswds/uswds/dist/fonts/
    - source: ./node_modules/@uswds/uswds/dist/img/usa-icons/expand_less.svg
      target: static/node_modules/@uswds/uswds/dist/img/usa-icons/expand_less.svg
    - source: ./node_modules/@uswds/uswds/dist/img/usa-icons/expand_more.svg
      target: static/node_modules/@uswds/uswds/dist/img/usa-icons/expand_more.svg
    - source: ./node_modules/@uswds/uswds/dist/img/usa-icons/unfold_less.svg
      target: static/node_modules/@uswds/uswds/dist/img/usa-icons/unfold_less.svg
    - source: ./node_modules/@uswds/uswds/dist/img/usa-icons/unfold_more.svg
      target: static/node_modules/@uswds/uswds/dist/img/usa-icons/unfold_more.svg
    - source: ./node_modules/@uswds/uswds/dist/img/icon-dot-gov.svg
      target: static/node_modules/@uswds/uswds/dist/img/icon-dot-gov.svg
    - source: ./node_modules/@uswds/uswds/dist/img/icon-https.svg
      target: static/node_modules/@uswds/uswds/dist/img/icon-https.svg
    - source: ./node_modules/@uswds/uswds/dist/img/sprite.svg
      target: static/node_modules/@uswds/uswds/dist/img/sprite.svg
    - source: ./node_modules/@uswds/uswds/dist/img/us_flag_small.png
      target: static/node_modules/@uswds/uswds/dist/img/us_flag_small.png
    - source: ./node_modules/@uswds/uswds/dist/js/
      target: static/node_modules/@uswds/uswds/dist/js/
disable404: true
security:
  exec:
    # Add HOME to allowed environment variables list for compatibility with
    # asdf-nodejs for postcss.
    osEnv:
      - "(?i)^(PATH|PATHEXT|APPDATA|TMP|TEMP|TERM|HOME)$"
