baseURL: /
languageCode: en-us
title: api.data.gov
disableKinds:
  - RSS
  - section
  - taxonomy
  - term
params:
  githubRepoUrl: https://github.com/18F/api.data.gov
  apiUmbrellaContactApiKey: DEMO_KEY
  apiUmbrellaSignupApiKey: DEMO_KEY
  csp:
    defaultSrc:
      - "'self'"
    scriptSrc:
      - "'self'"
      # DAP
      - https://dap.digitalgov.gov

      # Google Tag Manager, GA4:
      # https://developers.google.com/tag-platform/tag-manager/csp#google_analytics_4_google_analytics
      - https://*.googletagmanager.com

      # Universal Analytics
      - https://www.google-analytics.com
      - https://ssl.google-analytics.com

      # Google Analytics snippet (one for dev, one for minified build).
      - "'sha256-mv2dNKWU2RZMrC9ORr0aby1yXgZ/xQWeRNDk6vy/cL8='"
      - "'sha256-+1RoZRAphnNzPiW07Ff8Tr475vaH1/HWgpt/tg+K7Lo='"
    imgSrc:
      - "'self'"

      # Google Tag Manager, GA4:
      # https://developers.google.com/tag-platform/tag-manager/csp#google_analytics_4_google_analytics
      - https://*.google-analytics.com
      - https://*.googletagmanager.com

      # Data.gov template images
      - https://s3-us-gov-west-1.amazonaws.com/cg-0817d6e3-93c4-4de8-8b32-da6919464e61/
    connectSrc:
      - "'self'"
      # Google Tag Manager, GA4:
      # https://developers.google.com/tag-platform/tag-manager/csp#google_analytics_4_google_analytics
      - https://*.google-analytics.com
      - https://*.analytics.google.com
      - https://*.googletagmanager.com
      - https://analytics.google.com
    frameSrc:
      - "'self'"

      # Google Tag Manager, GA4:
      # https://developers.google.com/tag-platform/tag-manager/csp#google_analytics_4_google_analytics
      - https://www.googletagmanager.com/
    styleSrc:
      - "'self'"

      # Google Fonts
      - https://fonts.googleapis.com
    fontSrc:
      - "'self'"

      # Google Fonts
      - https://fonts.gstatic.com
markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    style: github
menu:
  main:
    - identifier: docs
      name: API Docs
      pageRef: /docs/
    - identifier: signup
      name: API Key Sign Up
      pageRef: /signup.html
sectionPagesMenu: main
module:
  mounts:
    - source: content
      target: content
    - source: static
      target: static
    - source: layouts
      target: layouts
    - source: data
      target: data
    - source: assets
      target: assets
    - source: i18n
      target: i18n
    - source: archetypes
      target: archetypes
    - source: ./node_modules/@uswds/uswds/dist/fonts/
      target: static/node_modules/@uswds/uswds/dist/fonts/
    - source: ./node_modules/@uswds/uswds/dist/img/usa-icons/expand_less.svg
      target: static/node_modules/@uswds/uswds/dist/img/usa-icons/expand_less.svg
    - source: ./node_modules/@uswds/uswds/dist/img/usa-icons/expand_more.svg
      target: static/node_modules/@uswds/uswds/dist/img/usa-icons/expand_more.svg
    - source: ./node_modules/@uswds/uswds/dist/img/usa-icons/unfold_less.svg
      target: static/node_modules/@uswds/uswds/dist/img/usa-icons/unfold_less.svg
    - source: ./node_modules/@uswds/uswds/dist/img/usa-icons/unfold_more.svg
      target: static/node_modules/@uswds/uswds/dist/img/usa-icons/unfold_more.svg
    - source: ./node_modules/@uswds/uswds/dist/img/icon-dot-gov.svg
      target: static/node_modules/@uswds/uswds/dist/img/icon-dot-gov.svg
    - source: ./node_modules/@uswds/uswds/dist/img/icon-https.svg
      target: static/node_modules/@uswds/uswds/dist/img/icon-https.svg
    - source: ./node_modules/@uswds/uswds/dist/img/sprite.svg
      target: static/node_modules/@uswds/uswds/dist/img/sprite.svg
    - source: ./node_modules/@uswds/uswds/dist/img/us_flag_small.png
      target: static/node_modules/@uswds/uswds/dist/img/us_flag_small.png
    - source: ./node_modules/@uswds/uswds/dist/js/
      target: static/node_modules/@uswds/uswds/dist/js/
disable404: true
security:
  exec:
    # Add HOME to allowed environment variables list for compatibility with
    # asdf-nodejs for postcss.
    osEnv:
      - "(?i)^(PATH|PATHEXT|APPDATA|TMP|TEMP|TERM|HOME)$"
