baseURL: /
languageCode: en-us
title: My New Hugo Site
params:
  githubRepoUrl: https://github.com/NREL/api-umbrella
  apiUmbrellaApiKey: DEMO_KEY
markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    style: github
menu:
  main:
    - identifier: docs
      name: API Docs
      pageRef: /docs/
    - identifier: signup
      name: API Key Signup
      pageRef: /signup.html
sectionPagesMenu: main
module:
  mounts:
    - source: content
      target: content
    - source: static
      target: static
    - source: layouts
      target: layouts
    - source: data
      target: data
    - source: assets
      target: assets
    - source: i18n
      target: i18n
    - source: archetypes
      target: archetypes
    - source: ./vendor/data.gov/roots-nextdatagov/assets/img/logo.png
      target: static/img/logo.png
disable404: true
