services:
  web:
    build:
      context: .
    volumes:
      - .:/app
      - pnpm_cache:/usr/local/pnpm
      - npm_cache:/usr/local/node_modules
    ports:
      - "4490:4490"
      - "4491:4491"
volumes:
  pnpm_cache:
  npm_cache:
